### ISSUE TITLE
SystemOverwrites .makeWindow

### ISSUE THREAD

**Issue by dyfer** [scztt/ServerView.quark#2]
While ServerView is of course more powerful than the regular server gui, it does overwrite Server's .makeGui method. This prevents me from embedding the basic gui in another view, and thus makes my old code not work as it should. Would you consider not overwriting the built-in method and instead adding a new one?

**Comment by scztt** [comment]
👍 Overriding the server window should be done via `Platform.makeServerWindowAction` I think - I'll fix this.

**Comment by dyfer** [comment]
Hey Scott,
Are you still considering removing this overwrite by any chance?
Thanks!
Marcin

**Comment by scztt** [comment]
Hey, apologies! I had this change around but never pushed - let me know if this addresses!
